version: 2.1
orbs:
   codecov: codecov/codecov@1.0.4
jobs:
   build:
      working_directory: ~/JBehave-BerlinClock
      docker:
         - image: circleci/openjdk:8-jdk-browsers
      steps:
         - checkout
         - restore_cache:
            key: JBehave-BerlinClock-{{ checksum "pom.xml" }}
         - run: mvn dependency:go-offline
         - save_cache: 
            paths:
               - ~/.m2
            key: JBehave-BerlinClock-{{ checksum "pom.xml" }}
         - run: mvn package
         - store_test_results: 
            path: target/surefire-reports
         - codecov/upload:
            file: target/my-reports/jacoco.xml
            token: a64cf1be-812f-45b2-b80e-efff6fcd2471
         - store_artifacts: 
            path: target/BerlinClock-0.0.1-SNAPSHOT.jar